export const books = [
  {
    isbn: "9780143127550",
    cover: "books/to-kill-a-mockingbird.png",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publisher: "J. B. Lippincott & Co.",
    publishedDate: "July 11, 1960",
    genre: "Classic",
    keySearchWords: ["racism", "justice", "coming-of-age"],
  },
  {
    isbn: "9780061120084",
cover: "books/1984.png",
    title: "1984",
    author: "George Orwell",
    publisher: "Secker & Warburg",
    publishedDate: "June 8, 1949",
    genre: "Dystopian",
    keySearchWords: ["totalitarianism", "surveillance", "thought control"],
  },
  {
    isbn: "9798404767230",
 cover: "books/pride-and-prejudice.png",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publisher: "T. Egerton, Whitehall",
    publishedDate: "January 28, 1813",
    genre: "Romance",
    keySearchWords: ["love", "society", "marriage"],
  },
  {
    isbn: "9780316769174",
    cover: "books/catcher-in-the-rye.png",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publisher: "Little, Brown and Company",
    publishedDate: "July 16, 1951",
    genre: "Coming-of-age",
    keySearchWords: ["adolescence", "alienation", "identity"],
  },
  {
    isbn: "9780544273443",
cover: "books/tlotr.png",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publisher: "Allen & Unwin",
    publishedDate: "July 29, 1954",
    genre: "Fantasy",
    keySearchWords: ["epic", "adventure", "magic"],
  },
  {
    isbn: "9780547928227",
    cover: "books/the-hobbit.png",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publisher: "George Allen & Unwin",
    publishedDate: "September 21, 1937",
    genre: "Fantasy",
    keySearchWords: ["adventure", "quest", "dragon"],
  },
  {
    isbn: "9781408855652",
    cover: "books/harry-potter-philosophers-stone.png",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    publisher: "Bloomsbury Publishing",
    publishedDate: "June 26, 1997",
    genre: "Fantasy",
    keySearchWords: ["magic", "wizard", "friendship"],
  },
  {
    isbn: "9798351145013",
    cover: "books/the-great-gatsby.png",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publisher: "Charles Scribner's Sons",
    publishedDate: "April 10, 1925",
    genre: "Historical fiction",
    keySearchWords: ["wealth", "love", "American Dream"],
  },
  {
    isbn: "9780143105954",
   cover: "books/moby-dick-or-the-whale.png",
    title: "Moby-Dick; or, The Whale",
    author: "Herman Melville",
    publisher: "Richard Bentley (UK)",
    publishedDate: "October 18, 1851",
    genre: "Adventure",
    keySearchWords: ["whale", "obsession", "seafaring"],
  },
  {
    isbn: "9780060850524",
    cover: "books/brave_new_world.png",
    title: "Brave New World",
    author: "Aldous Huxley",
    publisher: "Chatto & Windus",
    publishedDate: "February 17, 1932",
    genre: "Dystopian",
    keySearchWords: ["society", "technology", "social control"],
  },
  {
    isbn: "9780486280615",
   cover: "books/adventures-of-huckleberry-finn.png",
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    publisher: "Chatto & Windus",
    publishedDate: "December 10, 1884",
    genre: "Adventure",
    keySearchWords: ["Mississippi River", "friendship", "race"],
  },
  {
    isbn: "9780064471046",
 cover:
      "books/the-lion-the-witch-and-the-wardrobe-the-chronicles-of-narnia-book.png",
    title: "The Lion, the Witch & the Wardrobe",
    author: "C.S. Lewis",
    publisher: "Geoffrey Bles",
    publishedDate: "16 October 1950",
    genre: "Fantasy",
    keySearchWords: ["magic", "adventure", "Christian symbolism"],
  },
  {
    isbn: "9780062315007",
 cover: "books/the-alchemist.png",
    title: "The Alchemist",
    author: "Paulo Coelho",
    publisher: "HarperCollins",
    publishedDate: "1988",
    genre: "Fable",
    keySearchWords: ["journey", "dreams", "spirituality"],
  },
  {
    isbn: "9798374008258",
    cover: "books/the-picture-of-dorian-gray.png",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publisher: "Lippincott's Monthly Magazine",
    publishedDate: "June 20, 1890",
    genre: "Gothic",
    keySearchWords: ["vanity", "corruption", "art"],
  },
  {
    isbn: "9781512308051",
 cover: "books/frankenstein.png",
    title: "Frankenstein",
    author: "Mary Shelley",
    publisher: "Lackington, Hughes, Harding, Mavor & Jones",
    publishedDate: "January 1, 1818",
    genre: "Gothic",
    keySearchWords: ["science fiction", "creation", "monstrosity"],
  },
  {
    isbn: "9780439023528",
cover: "books/the-hunger-games.png",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    publisher: "Scholastic Corporation",
    publishedDate: "September 14, 2008",
    genre: "Dystopian",
    keySearchWords: ["survival", "oppression", "dystopia"],
  },
  {
    isbn: "9780307588371",
 cover: "books/gone-girl.png",
    title: "Gone Girl",
    author: "Gillian Flynn",
    publisher: "Crown Publishing Group",
    publishedDate: "June 5, 2012",
    genre: "Psychological thriller",
    keySearchWords: ["mystery", "marriage", "deception"],
  },
  {
    isbn: "9780698185395",
  cover: "books/the-girl-on-the-train.png",
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    publisher: "Riverhead Books",
    publishedDate: "January 13, 2015",
    genre: "Psychological thriller",
    keySearchWords: ["unreliable narrator", "missing person", "secrets"],
  },
  {
    isbn: "9780375842207",
    cover: "books/the-book-thief.png",
    title: "The Book Thief",
    author: "Markus Zusak",
    publisher: "Picador",
    publishedDate: "March 14, 2005",
    genre: "Historical fiction",
    keySearchWords: ["World War II", "books", "resilience"],
  },
  {
    isbn: "9781594631931",
    cover: "books/the-kite-runner.png",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    publisher: "Riverhead Books",
    publishedDate: "May 29, 2003",
    genre: "Historical fiction",
    keySearchWords: ["friendship", "redemption", "Afghanistan"],
  },
  {
    isbn: "9780274808328",
    cover: "books/the-da-vinci-code.png",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    publisher: "Doubleday",
    publishedDate: "March 18, 2003",
    genre: "Mystery",
    keySearchWords: ["art", "conspiracy", "religion"],
  },
  {
    isbn: "9780142424179",
    cover: "books/the-fault-in-our-stars-black.png",
    title: "The Fault in Our Stars",
    author: "John Green",
    publisher: "Dutton Books",
    publishedDate: "January 10, 2012",
    genre: "Young adult",
    keySearchWords: ["cancer", "love", "tragedy"],
  },
  {
    isbn: "9780425232200",
    cover: "books/the-help.png",
    title: "The Help",
    author: "Kathryn Stockett",
    publisher: "Putnam",
    publishedDate: "February 10, 2009",
    genre: "Historical fiction",
    keySearchWords: ["civil rights", "segregation", "friendship"],
  },
  {
    isbn: "9780385737951",
    cover: "books/maze-runner.png",
    title: "The Maze Runner",
    author: "James Dashner",
    publisher: "Delacorte Press",
    publishedDate: "October 6, 2009",
    genre: "Dystopian",
    keySearchWords: ["amnesia", "mystery", "post-apocalyptic"],
  },
  {
    isbn: "9780307949486",
    cover: "books/the-girl-with-the-dragon-tattoo.png",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    publisher: "Norstedts Förlag",
    publishedDate: "2005",
    genre: "Crime",
    keySearchWords: ["mystery", "investigation", "computer hacking"],
  },
  {
    isbn: "9780544336261",
    cover: "books/the-giver.png",
    title: "The Giver",
    author: "Lois Lowry",
    publisher: "Houghton Mifflin",
    publishedDate: "April 26, 1993",
    genre: "Dystopian",
    keySearchWords: ["memory", "conformity", "utopia"],
  },
  {
    isbn: "9780345806789",
    cover: "books/the-shining.png",
    title: "The Shining",
    author: "Stephen King",
    publisher: "Doubleday",
    publishedDate: "January 28, 1977",
    genre: "Horror",
    keySearchWords: ["haunted hotel", "madness", "isolation"],
  },
  {
    isbn: "9780316168816",
    cover: "books/girl-with-a-pearl-earring.png",
    title: "The Girl with the Pearl Earring",
    author: "Tracy Chevalier",
    publisher: "HarperCollins",
    publishedDate: "January 1, 1999",
    genre: "Historical fiction",
    keySearchWords: ["art", "Vermeer", "forbidden love"],
  },
  {

    isbn: "",
    cover: "books/the-lovely-bones.png",
    title: "The Lovely Bones",
    author: "Alice Sebold",
    publisher: "Little, Brown and Company",
    publishedDate: "July 3, 2002",
    genre: "Mystery",
    keySearchWords: ["afterlife", "grief", "murder"],
  },
  {
    isbn: "9780307387899",
    cover: "books/the-road.png",
    title: "The Road",
    author: "Cormac McCarthy",
    publisher: "Alfred A. Knopf",
    publishedDate: "September 26, 2006",
    genre: "Post-apocalyptic",
    keySearchWords: ["father-son relationship", "survival", "desolation"],
  },
  {
    isbn: "9780385490818",
    cover: "books/the-handmaids-tale.png",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    publisher: "McClelland and Stewart",
    publishedDate: "1985",
    genre: "Dystopian",
    keySearchWords: ["oppression", "feminism", "reproduction"],
  },
  {
    isbn: "9780274992379",
    cover: "books/use-of-weapons.png",
    title: "Use of Weapons",
    author: "Iain M. Banks",
    publisher: "Orbit",
    publishedDate: "1990",
    genre: "Science Fiction",
    keySearchWords: [
      "Space Opera",
      "Artificial Intelligence",
      "Military",
      "Complex Narrative",
    ],
  },
  {
    isbn: "9798374735512",
    cover: "books/great-expectations.png",

    title: "Great Expectations",
    author: "Charles Dickens",
    publisher: "Chapman & Hall",
    publishedDate: "1861",
    genre: "Historical Fiction",
    keySearchWords: ["Coming of Age", "Social Class", "Love", "Ambition"],
  },
];
